package g_exception;

public class Exception_03 {

	public static void main(String[] args) {
		int a=3;
		int b=0;
		
		System.out.println(a);
		try{
			System.out.println(a/b);
			System.out.println(b);
			System.out.println("완료");
		}catch(ArithmeticException e){
			
		}catch (Exception e) {
			
		}

	}

}
